name: RescueGroups API check

on:
  push:
    # We are doing this for testing purposes, but when we start posting, we should remove this line
    branches:
      [rescue_groups_api_patch]
  workflow_dispatch:
  schedule:
    # Every 4 hours
    - cron: "0 */4 * * *"

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install --break-system-packages -r requirements.txt

      - name: Call RescueGroups API
        env:
          CUTEPETSBOSTON_RESCUEGROUPS_API_KEY: ${{ secrets.CUTEPETSBOSTON_RESCUEGROUPS_API_KEY }}
          INSTAGRAM_HANDLE: ${{ secrets.INSTAGRAM_HANDLE }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: |
          pwd
          ls
          python ./main.py
