name: RescueGroups API check

on:
  push:
    branches: [ mw/test-workflow, j2_test ]
  workflow_dispatch:
  schedule:
    # Every 4 hours
    - cron: "0 */4 * * *"

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install --upgrade requests

      - name: Call RescueGroups API
        env:
          ACCESS_KEY: ${{ secrets.CUTEPETSBOSTON_RESCUEGROUPS_API_KEY }}
        run: |
          pwd
          ls
          python ./main.py